# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RDF(object):
    def setupUi(self, RDF):
        RDF.setObjectName("RDF")
        RDF.resize(1507, 736)
        RDF.setMinimumSize(QtCore.QSize(0, 0))
        RDF.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(RDF)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CORPO = QtWidgets.QFrame(self.centralwidget)
        self.CORPO.setStyleSheet("background-color: rgb(197, 208, 200);")
        self.CORPO.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CORPO.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CORPO.setObjectName("CORPO")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.CORPO)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_menu = QtWidgets.QFrame(self.CORPO)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(250)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_menu.sizePolicy().hasHeightForWidth())
        self.frame_menu.setSizePolicy(sizePolicy)
        self.frame_menu.setMinimumSize(QtCore.QSize(55, 50))
        self.frame_menu.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.frame_menu.setFont(font)
        self.frame_menu.setStyleSheet("background-color: rgb(3, 3, 3);\n"
"color: rgb(235, 235, 235);")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.frame_menu)
        self.frame.setMinimumSize(QtCore.QSize(50, 0))
        self.frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 3, 0, 2)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_luzes = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_luzes.sizePolicy().hasHeightForWidth())
        self.btn_luzes.setSizePolicy(sizePolicy)
        self.btn_luzes.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_luzes.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.btn_luzes.setFont(font)
        self.btn_luzes.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_luzes.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(40,40, 40);\n"
"    border:0px solid rgb(150, 150, 150);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(19, 106, 236);\n"
"    border:0px solid rgb(90, 90, 90);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(200, 200, 200);\n"
"    border:0px solid rgb(90, 90, 90);\n"
"}")
        self.btn_luzes.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_luzes.setObjectName("btn_luzes")
        self.verticalLayout_2.addWidget(self.btn_luzes)
        self.btn_grafico = QtWidgets.QPushButton(self.frame)
        self.btn_grafico.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_grafico.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.btn_grafico.setFont(font)
        self.btn_grafico.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(40, 40,40);\n"
"    border:0px solid rgb(150, 150, 150);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(19, 106, 236);\n"
"    border:0px solid rgb(90, 90, 90);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(200, 200, 200);\n"
"    border:0px solid rgb(90, 90, 90);\n"
"}")
        self.btn_grafico.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_grafico.setObjectName("btn_grafico")
        self.verticalLayout_2.addWidget(self.btn_grafico)
        self.verticalLayout_3.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.frame_menu)
        self.CONTEUDO = QtWidgets.QFrame(self.CORPO)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.CONTEUDO.setFont(font)
        self.CONTEUDO.setMouseTracking(False)
        self.CONTEUDO.setStyleSheet("background-color: rgb(43, 43, 43);\n"
"color: rgb(235, 235, 235);")
        self.CONTEUDO.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CONTEUDO.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CONTEUDO.setObjectName("CONTEUDO")
        self.luz_frame = QtWidgets.QFrame(self.CONTEUDO)
        self.luz_frame.setGeometry(QtCore.QRect(4, 0, 600, 600))
        self.luz_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.luz_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.luz_frame.setObjectName("luz_frame")
        self.frame_lmpada = QtWidgets.QFrame(self.luz_frame)
        self.frame_lmpada.setGeometry(QtCore.QRect(10, 40, 141, 91))
        self.frame_lmpada.setStyleSheet("    \n"
"    background-color: rgb(34, 34, 34);\n"
"    border:1px solid rgb(30, 30, 50);\n"
"    border-radius:5px;\n"
"")
        self.frame_lmpada.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lmpada.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lmpada.setObjectName("frame_lmpada")
        self.btn_liga = QtWidgets.QPushButton(self.frame_lmpada)
        self.btn_liga.setEnabled(True)
        self.btn_liga.setGeometry(QtCore.QRect(3, 2, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_liga.setFont(font)
        self.btn_liga.setStatusTip("")
        self.btn_liga.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(90, 90, 90);\n"
"    border:2px solid rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(4, 134, 4);\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}")
        self.btn_liga.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_liga.setCheckable(False)
        self.btn_liga.setChecked(False)
        self.btn_liga.setAutoExclusive(False)
        self.btn_liga.setAutoDefault(False)
        self.btn_liga.setDefault(False)
        self.btn_liga.setFlat(True)
        self.btn_liga.setObjectName("btn_liga")
        self.btn_desliga = QtWidgets.QPushButton(self.frame_lmpada)
        self.btn_desliga.setEnabled(True)
        self.btn_desliga.setGeometry(QtCore.QRect(3, 34, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_desliga.setFont(font)
        self.btn_desliga.setStatusTip("")
        self.btn_desliga.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(90, 90, 90); \n"
"    border:2px solid rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(153, 0, 0);\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}")
        self.btn_desliga.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_desliga.setCheckable(False)
        self.btn_desliga.setChecked(False)
        self.btn_desliga.setAutoExclusive(False)
        self.btn_desliga.setAutoDefault(False)
        self.btn_desliga.setDefault(False)
        self.btn_desliga.setFlat(True)
        self.btn_desliga.setObjectName("btn_desliga")
        self.label = QtWidgets.QLabel(self.frame_lmpada)
        self.label.setGeometry(QtCore.QRect(30, 70, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_desligado = QtWidgets.QFrame(self.frame_lmpada)
        self.frame_desligado.setGeometry(QtCore.QRect(80, 5, 42, 42))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frame_desligado.setFont(font)
        self.frame_desligado.setStyleSheet("\n"
"    background-color: rgb(222, 3, 10);\n"
"    border:0px solid rgb(90, 90, 90);\n"
"    border-radius:20px;\n"
"")
        self.frame_desligado.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_desligado.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_desligado.setObjectName("frame_desligado")
        self.text_desligado = QtWidgets.QLabel(self.frame_desligado)
        self.text_desligado.setGeometry(QtCore.QRect(6, 10, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.text_desligado.setFont(font)
        self.text_desligado.setAutoFillBackground(False)
        self.text_desligado.setStyleSheet("    border:0px solid rgb(90, 90, 90);\n"
"    border-radius:20px;")
        self.text_desligado.setObjectName("text_desligado")
        self.frame_ligado = QtWidgets.QFrame(self.frame_lmpada)
        self.frame_ligado.setGeometry(QtCore.QRect(80, 5, 42, 42))
        self.frame_ligado.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(3, 222, 10);\n"
"    border:0px solid rgb(0, 90, 90);\n"
"    border-radius:20px;\n"
"}")
        self.frame_ligado.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ligado.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ligado.setObjectName("frame_ligado")
        self.text_estado = QtWidgets.QLabel(self.frame_ligado)
        self.text_estado.setGeometry(QtCore.QRect(8, 10, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.text_estado.setFont(font)
        self.text_estado.setStyleSheet("    border:0px solid rgb(90, 90, 90);\n"
"    border-radius:20px;")
        self.text_estado.setObjectName("text_estado")
        self.frame_ligado.raise_()
        self.btn_liga.raise_()
        self.btn_desliga.raise_()
        self.label.raise_()
        self.frame_desligado.raise_()
        self.frame_lmpada_2 = QtWidgets.QFrame(self.luz_frame)
        self.frame_lmpada_2.setGeometry(QtCore.QRect(160, 40, 141, 91))
        self.frame_lmpada_2.setStyleSheet("    \n"
"    background-color: rgb(34, 34, 34);\n"
"    border:1px solid rgb(30, 30, 50);\n"
"    border-radius:5px;\n"
"")
        self.frame_lmpada_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lmpada_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lmpada_2.setObjectName("frame_lmpada_2")
        self.btn_liga_2 = QtWidgets.QPushButton(self.frame_lmpada_2)
        self.btn_liga_2.setEnabled(True)
        self.btn_liga_2.setGeometry(QtCore.QRect(3, 2, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_liga_2.setFont(font)
        self.btn_liga_2.setStatusTip("")
        self.btn_liga_2.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(90, 90, 90);\n"
"    border:2px solid rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(4, 134, 4);\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}")
        self.btn_liga_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_liga_2.setCheckable(False)
        self.btn_liga_2.setChecked(False)
        self.btn_liga_2.setAutoExclusive(False)
        self.btn_liga_2.setAutoDefault(False)
        self.btn_liga_2.setDefault(False)
        self.btn_liga_2.setFlat(True)
        self.btn_liga_2.setObjectName("btn_liga_2")
        self.btn_desliga_2 = QtWidgets.QPushButton(self.frame_lmpada_2)
        self.btn_desliga_2.setEnabled(True)
        self.btn_desliga_2.setGeometry(QtCore.QRect(3, 34, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_desliga_2.setFont(font)
        self.btn_desliga_2.setStatusTip("")
        self.btn_desliga_2.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(90, 90, 90); \n"
"    border:2px solid rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(153, 0, 0);\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}")
        self.btn_desliga_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_desliga_2.setCheckable(False)
        self.btn_desliga_2.setChecked(False)
        self.btn_desliga_2.setAutoExclusive(False)
        self.btn_desliga_2.setAutoDefault(False)
        self.btn_desliga_2.setDefault(False)
        self.btn_desliga_2.setFlat(True)
        self.btn_desliga_2.setObjectName("btn_desliga_2")
        self.label_2 = QtWidgets.QLabel(self.frame_lmpada_2)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.frame_desligado_2 = QtWidgets.QFrame(self.frame_lmpada_2)
        self.frame_desligado_2.setGeometry(QtCore.QRect(80, 5, 42, 42))
        self.frame_desligado_2.setStyleSheet("\n"
"    background-color: rgb(222, 3, 10);\n"
"    border:0px solid rgb(90, 90, 90);\n"
"    border-radius:20px;\n"
"")
        self.frame_desligado_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_desligado_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_desligado_2.setObjectName("frame_desligado_2")
        self.text_desligado_2 = QtWidgets.QLabel(self.frame_desligado_2)
        self.text_desligado_2.setGeometry(QtCore.QRect(6, 10, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_desligado_2.setFont(font)
        self.text_desligado_2.setAutoFillBackground(False)
        self.text_desligado_2.setStyleSheet("    border:0px solid rgb(90, 90, 90);\n"
"    border-radius:20px;")
        self.text_desligado_2.setObjectName("text_desligado_2")
        self.frame_ligado_2 = QtWidgets.QFrame(self.frame_lmpada_2)
        self.frame_ligado_2.setGeometry(QtCore.QRect(80, 5, 42, 42))
        self.frame_ligado_2.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(3, 222, 10);\n"
"    border:0px solid rgb(0, 90, 90);\n"
"    border-radius:20px;\n"
"}")
        self.frame_ligado_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ligado_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ligado_2.setObjectName("frame_ligado_2")
        self.text_estado_3 = QtWidgets.QLabel(self.frame_ligado_2)
        self.text_estado_3.setGeometry(QtCore.QRect(8, 10, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_estado_3.setFont(font)
        self.text_estado_3.setStyleSheet("    border:0px solid rgb(90, 90, 90);\n"
"    border-radius:20px;")
        self.text_estado_3.setObjectName("text_estado_3")
        self.frame_ligado_2.raise_()
        self.btn_liga_2.raise_()
        self.btn_desliga_2.raise_()
        self.label_2.raise_()
        self.frame_desligado_2.raise_()
        self.label_9 = QtWidgets.QLabel(self.luz_frame)
        self.label_9.setGeometry(QtCore.QRect(130, 10, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.luz_frame)
        self.label_10.setGeometry(QtCore.QRect(20, 160, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.luz_frame)
        self.label_11.setGeometry(QtCore.QRect(20, 310, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.luz_frame)
        self.label_12.setGeometry(QtCore.QRect(180, 160, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.luz_frame)
        self.label_13.setGeometry(QtCore.QRect(180, 310, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.frame_lmpada_5 = QtWidgets.QFrame(self.luz_frame)
        self.frame_lmpada_5.setGeometry(QtCore.QRect(10, 190, 141, 91))
        self.frame_lmpada_5.setStyleSheet("    \n"
"    background-color: rgb(34, 34, 34);\n"
"    border:1px solid rgb(30, 30, 50);\n"
"    border-radius:5px;\n"
"")
        self.frame_lmpada_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lmpada_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lmpada_5.setObjectName("frame_lmpada_5")
        self.btn_liga_7 = QtWidgets.QPushButton(self.frame_lmpada_5)
        self.btn_liga_7.setEnabled(True)
        self.btn_liga_7.setGeometry(QtCore.QRect(3, 2, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_liga_7.setFont(font)
        self.btn_liga_7.setStatusTip("")
        self.btn_liga_7.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(90, 90, 90);\n"
"    border:2px solid rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(4, 134, 4);\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}")
        self.btn_liga_7.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_liga_7.setCheckable(False)
        self.btn_liga_7.setChecked(False)
        self.btn_liga_7.setAutoExclusive(False)
        self.btn_liga_7.setAutoDefault(False)
        self.btn_liga_7.setDefault(False)
        self.btn_liga_7.setFlat(True)
        self.btn_liga_7.setObjectName("btn_liga_7")
        self.btn_desliga_7 = QtWidgets.QPushButton(self.frame_lmpada_5)
        self.btn_desliga_7.setEnabled(True)
        self.btn_desliga_7.setGeometry(QtCore.QRect(3, 34, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_desliga_7.setFont(font)
        self.btn_desliga_7.setStatusTip("")
        self.btn_desliga_7.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(90, 90, 90); \n"
"    border:2px solid rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(153, 0, 0);\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}")
        self.btn_desliga_7.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_desliga_7.setCheckable(False)
        self.btn_desliga_7.setChecked(False)
        self.btn_desliga_7.setAutoExclusive(False)
        self.btn_desliga_7.setAutoDefault(False)
        self.btn_desliga_7.setDefault(False)
        self.btn_desliga_7.setFlat(True)
        self.btn_desliga_7.setObjectName("btn_desliga_7")
        self.label_7 = QtWidgets.QLabel(self.frame_lmpada_5)
        self.label_7.setGeometry(QtCore.QRect(30, 70, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.frame_desligado_7 = QtWidgets.QFrame(self.frame_lmpada_5)
        self.frame_desligado_7.setGeometry(QtCore.QRect(80, 5, 42, 42))
        self.frame_desligado_7.setStyleSheet("\n"
"    background-color: rgb(222, 3, 10);\n"
"    border:0px solid rgb(90, 90, 90);\n"
"    border-radius:20px;\n"
"")
        self.frame_desligado_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_desligado_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_desligado_7.setObjectName("frame_desligado_7")
        self.text_desligado_7 = QtWidgets.QLabel(self.frame_desligado_7)
        self.text_desligado_7.setGeometry(QtCore.QRect(6, 10, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_desligado_7.setFont(font)
        self.text_desligado_7.setAutoFillBackground(False)
        self.text_desligado_7.setStyleSheet("    border:0px solid rgb(90, 90, 90);\n"
"    border-radius:20px;")
        self.text_desligado_7.setObjectName("text_desligado_7")
        self.frame_ligado_7 = QtWidgets.QFrame(self.frame_lmpada_5)
        self.frame_ligado_7.setGeometry(QtCore.QRect(80, 5, 42, 42))
        self.frame_ligado_7.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(3, 222, 10);\n"
"    border:0px solid rgb(0, 90, 90);\n"
"    border-radius:20px;\n"
"}")
        self.frame_ligado_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ligado_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ligado_7.setObjectName("frame_ligado_7")
        self.text_estado_8 = QtWidgets.QLabel(self.frame_ligado_7)
        self.text_estado_8.setGeometry(QtCore.QRect(8, 10, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_estado_8.setFont(font)
        self.text_estado_8.setStyleSheet("    border:0px solid rgb(90, 90, 90);\n"
"    border-radius:20px;")
        self.text_estado_8.setObjectName("text_estado_8")
        self.frame_ligado_7.raise_()
        self.btn_liga_7.raise_()
        self.btn_desliga_7.raise_()
        self.label_7.raise_()
        self.frame_desligado_7.raise_()
        self.frame_lmpada_6 = QtWidgets.QFrame(self.luz_frame)
        self.frame_lmpada_6.setGeometry(QtCore.QRect(160, 190, 141, 91))
        self.frame_lmpada_6.setStyleSheet("    \n"
"    background-color: rgb(34, 34, 34);\n"
"    border:1px solid rgb(30, 30, 50);\n"
"    border-radius:5px;\n"
"")
        self.frame_lmpada_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lmpada_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lmpada_6.setObjectName("frame_lmpada_6")
        self.btn_liga_8 = QtWidgets.QPushButton(self.frame_lmpada_6)
        self.btn_liga_8.setEnabled(True)
        self.btn_liga_8.setGeometry(QtCore.QRect(3, 2, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_liga_8.setFont(font)
        self.btn_liga_8.setStatusTip("")
        self.btn_liga_8.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(90, 90, 90);\n"
"    border:2px solid rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(4, 134, 4);\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}")
        self.btn_liga_8.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_liga_8.setCheckable(False)
        self.btn_liga_8.setChecked(False)
        self.btn_liga_8.setAutoExclusive(False)
        self.btn_liga_8.setAutoDefault(False)
        self.btn_liga_8.setDefault(False)
        self.btn_liga_8.setFlat(True)
        self.btn_liga_8.setObjectName("btn_liga_8")
        self.btn_desliga_8 = QtWidgets.QPushButton(self.frame_lmpada_6)
        self.btn_desliga_8.setEnabled(True)
        self.btn_desliga_8.setGeometry(QtCore.QRect(3, 34, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_desliga_8.setFont(font)
        self.btn_desliga_8.setStatusTip("")
        self.btn_desliga_8.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(90, 90, 90); \n"
"    border:2px solid rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(153, 0, 0);\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}")
        self.btn_desliga_8.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_desliga_8.setCheckable(False)
        self.btn_desliga_8.setChecked(False)
        self.btn_desliga_8.setAutoExclusive(False)
        self.btn_desliga_8.setAutoDefault(False)
        self.btn_desliga_8.setDefault(False)
        self.btn_desliga_8.setFlat(True)
        self.btn_desliga_8.setObjectName("btn_desliga_8")
        self.label_8 = QtWidgets.QLabel(self.frame_lmpada_6)
        self.label_8.setGeometry(QtCore.QRect(30, 70, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.frame_desligado_8 = QtWidgets.QFrame(self.frame_lmpada_6)
        self.frame_desligado_8.setGeometry(QtCore.QRect(80, 5, 42, 42))
        self.frame_desligado_8.setStyleSheet("\n"
"    background-color: rgb(222, 3, 10);\n"
"    border:0px solid rgb(90, 90, 90);\n"
"    border-radius:20px;\n"
"")
        self.frame_desligado_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_desligado_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_desligado_8.setObjectName("frame_desligado_8")
        self.text_desligado_8 = QtWidgets.QLabel(self.frame_desligado_8)
        self.text_desligado_8.setGeometry(QtCore.QRect(6, 10, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_desligado_8.setFont(font)
        self.text_desligado_8.setAutoFillBackground(False)
        self.text_desligado_8.setStyleSheet("    border:0px solid rgb(90, 90, 90);\n"
"    border-radius:20px;")
        self.text_desligado_8.setObjectName("text_desligado_8")
        self.frame_ligado_8 = QtWidgets.QFrame(self.frame_lmpada_6)
        self.frame_ligado_8.setGeometry(QtCore.QRect(80, 5, 42, 42))
        self.frame_ligado_8.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(3, 222, 10);\n"
"    border:0px solid rgb(0, 90, 90);\n"
"    border-radius:20px;\n"
"}")
        self.frame_ligado_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ligado_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ligado_8.setObjectName("frame_ligado_8")
        self.text_estado_9 = QtWidgets.QLabel(self.frame_ligado_8)
        self.text_estado_9.setGeometry(QtCore.QRect(8, 10, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_estado_9.setFont(font)
        self.text_estado_9.setStyleSheet("    border:0px solid rgb(90, 90, 90);\n"
"    border-radius:20px;")
        self.text_estado_9.setObjectName("text_estado_9")
        self.frame_ligado_8.raise_()
        self.btn_liga_8.raise_()
        self.btn_desliga_8.raise_()
        self.label_8.raise_()
        self.frame_desligado_8.raise_()
        self.frame_lmpada_7 = QtWidgets.QFrame(self.luz_frame)
        self.frame_lmpada_7.setGeometry(QtCore.QRect(10, 340, 141, 91))
        self.frame_lmpada_7.setStyleSheet("    \n"
"    background-color: rgb(34, 34, 34);\n"
"    border:1px solid rgb(30, 30, 50);\n"
"    border-radius:5px;\n"
"")
        self.frame_lmpada_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lmpada_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lmpada_7.setObjectName("frame_lmpada_7")
        self.btn_liga_9 = QtWidgets.QPushButton(self.frame_lmpada_7)
        self.btn_liga_9.setEnabled(True)
        self.btn_liga_9.setGeometry(QtCore.QRect(3, 2, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_liga_9.setFont(font)
        self.btn_liga_9.setStatusTip("")
        self.btn_liga_9.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(90, 90, 90);\n"
"    border:2px solid rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(4, 134, 4);\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}")
        self.btn_liga_9.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_liga_9.setCheckable(False)
        self.btn_liga_9.setChecked(False)
        self.btn_liga_9.setAutoExclusive(False)
        self.btn_liga_9.setAutoDefault(False)
        self.btn_liga_9.setDefault(False)
        self.btn_liga_9.setFlat(True)
        self.btn_liga_9.setObjectName("btn_liga_9")
        self.btn_desliga_9 = QtWidgets.QPushButton(self.frame_lmpada_7)
        self.btn_desliga_9.setEnabled(True)
        self.btn_desliga_9.setGeometry(QtCore.QRect(3, 34, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_desliga_9.setFont(font)
        self.btn_desliga_9.setStatusTip("")
        self.btn_desliga_9.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(90, 90, 90); \n"
"    border:2px solid rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(153, 0, 0);\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}")
        self.btn_desliga_9.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_desliga_9.setCheckable(False)
        self.btn_desliga_9.setChecked(False)
        self.btn_desliga_9.setAutoExclusive(False)
        self.btn_desliga_9.setAutoDefault(False)
        self.btn_desliga_9.setDefault(False)
        self.btn_desliga_9.setFlat(True)
        self.btn_desliga_9.setObjectName("btn_desliga_9")
        self.label_14 = QtWidgets.QLabel(self.frame_lmpada_7)
        self.label_14.setGeometry(QtCore.QRect(30, 70, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.frame_desligado_9 = QtWidgets.QFrame(self.frame_lmpada_7)
        self.frame_desligado_9.setGeometry(QtCore.QRect(80, 5, 42, 42))
        self.frame_desligado_9.setStyleSheet("\n"
"    background-color: rgb(222, 3, 10);\n"
"    border:0px solid rgb(90, 90, 90);\n"
"    border-radius:20px;\n"
"")
        self.frame_desligado_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_desligado_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_desligado_9.setObjectName("frame_desligado_9")
        self.text_desligado_9 = QtWidgets.QLabel(self.frame_desligado_9)
        self.text_desligado_9.setGeometry(QtCore.QRect(6, 10, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_desligado_9.setFont(font)
        self.text_desligado_9.setAutoFillBackground(False)
        self.text_desligado_9.setStyleSheet("    border:0px solid rgb(90, 90, 90);\n"
"    border-radius:20px;")
        self.text_desligado_9.setObjectName("text_desligado_9")
        self.frame_ligado_9 = QtWidgets.QFrame(self.frame_lmpada_7)
        self.frame_ligado_9.setGeometry(QtCore.QRect(80, 5, 42, 42))
        self.frame_ligado_9.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(3, 222, 10);\n"
"    border:0px solid rgb(0, 90, 90);\n"
"    border-radius:20px;\n"
"}")
        self.frame_ligado_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ligado_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ligado_9.setObjectName("frame_ligado_9")
        self.text_estado_10 = QtWidgets.QLabel(self.frame_ligado_9)
        self.text_estado_10.setGeometry(QtCore.QRect(8, 10, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_estado_10.setFont(font)
        self.text_estado_10.setStyleSheet("    border:0px solid rgb(90, 90, 90);\n"
"    border-radius:20px;")
        self.text_estado_10.setObjectName("text_estado_10")
        self.frame_ligado_9.raise_()
        self.btn_liga_9.raise_()
        self.btn_desliga_9.raise_()
        self.label_14.raise_()
        self.frame_desligado_9.raise_()
        self.frame_lmpada_8 = QtWidgets.QFrame(self.luz_frame)
        self.frame_lmpada_8.setGeometry(QtCore.QRect(160, 340, 141, 91))
        self.frame_lmpada_8.setStyleSheet("    \n"
"    background-color: rgb(34, 34, 34);\n"
"    border:1px solid rgb(30, 30, 50);\n"
"    border-radius:5px;\n"
"")
        self.frame_lmpada_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lmpada_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lmpada_8.setObjectName("frame_lmpada_8")
        self.btn_liga_10 = QtWidgets.QPushButton(self.frame_lmpada_8)
        self.btn_liga_10.setEnabled(True)
        self.btn_liga_10.setGeometry(QtCore.QRect(3, 2, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_liga_10.setFont(font)
        self.btn_liga_10.setStatusTip("")
        self.btn_liga_10.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(90, 90, 90);\n"
"    border:2px solid rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(4, 134, 4);\n"
"    border:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}")
        self.btn_liga_10.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_liga_10.setCheckable(False)
        self.btn_liga_10.setChecked(False)
        self.btn_liga_10.setAutoExclusive(False)
        self.btn_liga_10.setAutoDefault(False)
        self.btn_liga_10.setDefault(False)
        self.btn_liga_10.setFlat(True)
        self.btn_liga_10.setObjectName("btn_liga_10")
        self.btn_desliga_10 = QtWidgets.QPushButton(self.frame_lmpada_8)
        self.btn_desliga_10.setEnabled(True)
        self.btn_desliga_10.setGeometry(QtCore.QRect(3, 34, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_desliga_10.setFont(font)
        self.btn_desliga_10.setStatusTip("")
        self.btn_desliga_10.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(90, 90, 90); \n"
"    border:2px solid rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(153, 0, 0);\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}")
        self.btn_desliga_10.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_desliga_10.setCheckable(False)
        self.btn_desliga_10.setChecked(False)
        self.btn_desliga_10.setAutoExclusive(False)
        self.btn_desliga_10.setAutoDefault(False)
        self.btn_desliga_10.setDefault(False)
        self.btn_desliga_10.setFlat(True)
        self.btn_desliga_10.setObjectName("btn_desliga_10")
        self.label_15 = QtWidgets.QLabel(self.frame_lmpada_8)
        self.label_15.setGeometry(QtCore.QRect(30, 70, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.frame_desligado_10 = QtWidgets.QFrame(self.frame_lmpada_8)
        self.frame_desligado_10.setGeometry(QtCore.QRect(80, 5, 42, 42))
        self.frame_desligado_10.setStyleSheet("\n"
"    background-color: rgb(222, 3, 10);\n"
"    border:0px solid rgb(90, 90, 90);\n"
"    border-radius:20px;\n"
"")
        self.frame_desligado_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_desligado_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_desligado_10.setObjectName("frame_desligado_10")
        self.text_desligado_10 = QtWidgets.QLabel(self.frame_desligado_10)
        self.text_desligado_10.setGeometry(QtCore.QRect(6, 10, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_desligado_10.setFont(font)
        self.text_desligado_10.setAutoFillBackground(False)
        self.text_desligado_10.setStyleSheet("    border:0px solid rgb(90, 90, 90);\n"
"    border-radius:20px;")
        self.text_desligado_10.setObjectName("text_desligado_10")
        self.frame_ligado_10 = QtWidgets.QFrame(self.frame_lmpada_8)
        self.frame_ligado_10.setGeometry(QtCore.QRect(80, 5, 42, 42))
        self.frame_ligado_10.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(3, 222, 10);\n"
"    border:0px solid rgb(0, 90, 90);\n"
"    border-radius:20px;\n"
"}")
        self.frame_ligado_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ligado_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ligado_10.setObjectName("frame_ligado_10")
        self.text_estado_11 = QtWidgets.QLabel(self.frame_ligado_10)
        self.text_estado_11.setGeometry(QtCore.QRect(8, 10, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_estado_11.setFont(font)
        self.text_estado_11.setStyleSheet("    border:0px solid rgb(90, 90, 90);\n"
"    border-radius:20px;")
        self.text_estado_11.setObjectName("text_estado_11")
        self.frame_ligado_10.raise_()
        self.btn_liga_10.raise_()
        self.btn_desliga_10.raise_()
        self.label_15.raise_()
        self.frame_desligado_10.raise_()
        self.grafico_frame = QtWidgets.QFrame(self.CONTEUDO)
        self.grafico_frame.setGeometry(QtCore.QRect(0, 0, 600, 600))
        self.grafico_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.grafico_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.grafico_frame.setObjectName("grafico_frame")
        self.grafw = QtWidgets.QWidget(self.grafico_frame)
        self.grafw.setGeometry(QtCore.QRect(-1, -1, 600, 500))
        self.grafw.setObjectName("grafw")
        self.figure = QtWidgets.QLabel(self.grafw)
        self.figure.setGeometry(QtCore.QRect(0, 0, 600, 500))
        self.figure.setText("")
        self.figure.setPixmap(QtGui.QPixmap("Figure_1.png"))
        self.figure.setScaledContents(True)
        self.figure.setWordWrap(False)
        self.figure.setObjectName("figure")
        self.ATUALIZE = QtWidgets.QPushButton(self.grafw)
        self.ATUALIZE.setGeometry(QtCore.QRect(30, 120, 75, 23))
        self.ATUALIZE.setAutoRepeat(True)
        self.ATUALIZE.setAutoRepeatDelay(1000)
        self.ATUALIZE.setAutoRepeatInterval(1000)
        self.ATUALIZE.setObjectName("ATUALIZE")
        self.ATUALIZE.raise_()
        self.figure.raise_()
        self.grafico_frame.raise_()
        self.luz_frame.raise_()
        self.horizontalLayout.addWidget(self.CONTEUDO)
        self.verticalLayout.addWidget(self.CORPO)
        RDF.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RDF)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1507, 21))
        self.menubar.setObjectName("menubar")
        RDF.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(RDF)
        self.statusBar.setObjectName("statusBar")
        RDF.setStatusBar(self.statusBar)

        self.retranslateUi(RDF)
        QtCore.QMetaObject.connectSlotsByName(RDF)

    def retranslateUi(self, RDF):
        _translate = QtCore.QCoreApplication.translate
        RDF.setWindowTitle(_translate("RDF", "AUTOMAÇÃO-RDF"))
        self.btn_luzes.setText(_translate("RDF", "LUZES"))
        self.btn_grafico.setText(_translate("RDF", "GRÁFICO"))
        self.btn_liga.setText(_translate("RDF", "LIGA"))
        self.btn_desliga.setText(_translate("RDF", "DESL"))
        self.label.setText(_translate("RDF", "LAMPADA"))
        self.text_desligado.setText(_translate("RDF", "OFF"))
        self.text_estado.setText(_translate("RDF", "ON"))
        self.btn_liga_2.setText(_translate("RDF", "LIGA"))
        self.btn_desliga_2.setText(_translate("RDF", "DESL"))
        self.label_2.setText(_translate("RDF", "LAMPADA2"))
        self.text_desligado_2.setText(_translate("RDF", "OFF"))
        self.text_estado_3.setText(_translate("RDF", "ON"))
        self.label_9.setText(_translate("RDF", "SALA"))
        self.label_10.setText(_translate("RDF", "QUARTO 1"))
        self.label_11.setText(_translate("RDF", "QUARTO 2"))
        self.label_12.setText(_translate("RDF", "COZINHA"))
        self.label_13.setText(_translate("RDF", "TERRAÇO"))
        self.btn_liga_7.setText(_translate("RDF", "LIGA"))
        self.btn_desliga_7.setText(_translate("RDF", "DESL"))
        self.label_7.setText(_translate("RDF", "LAMPADA"))
        self.text_desligado_7.setText(_translate("RDF", "OFF"))
        self.text_estado_8.setText(_translate("RDF", "ON"))
        self.btn_liga_8.setText(_translate("RDF", "LIGA"))
        self.btn_desliga_8.setText(_translate("RDF", "DESL"))
        self.label_8.setText(_translate("RDF", "LAMPADA"))
        self.text_desligado_8.setText(_translate("RDF", "OFF"))
        self.text_estado_9.setText(_translate("RDF", "ON"))
        self.btn_liga_9.setText(_translate("RDF", "LIGA"))
        self.btn_desliga_9.setText(_translate("RDF", "DESL"))
        self.label_14.setText(_translate("RDF", "LAMPADA"))
        self.text_desligado_9.setText(_translate("RDF", "OFF"))
        self.text_estado_10.setText(_translate("RDF", "ON"))
        self.btn_liga_10.setText(_translate("RDF", "LIGA"))
        self.btn_desliga_10.setText(_translate("RDF", "DESL"))
        self.label_15.setText(_translate("RDF", "LAMPADA"))
        self.text_desligado_10.setText(_translate("RDF", "OFF"))
        self.text_estado_11.setText(_translate("RDF", "ON"))
        self.ATUALIZE.setText(_translate("RDF", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RDF = QtWidgets.QMainWindow()
    ui = Ui_RDF()
    ui.setupUi(RDF)
    RDF.show()
    sys.exit(app.exec_())
